networks:
  alkis_pg_net:
    driver: bridge

services:
  alkis_pg:
    image: ${ALKIS_PG_IMAGE:-alkis_pg}:${ALKIS_PG_TAG:-latest}
    container_name: ${ALKIS_PG_IMAGE:-alkis_pg}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-alkis_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - alkis_data:/var/lib/postgresql/data
    networks:
      - alkis_pg_net

volumes:
  alkis_data:
