networks:
  netinfra_pg_net:
    driver: bridge

services:
  netinfra_pg:
    image: ${IMAGE:-netinfra_pg}:${TAG:-latest}
    container_name: ${IMAGE:-netinfra_pg}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-netinfra_pg}
      DEFAULT_CRS: ${DEFAULT_CRS:-25832}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - netinfra_pg_data:/var/lib/postgresql/data
    networks:
      - netinfra_pg_net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-netinfra_pg}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  netinfra_pg_data:
