version: '3.8'

services:
  alkis_pg:
    image: ${ALKIS_PG_IMAGE}:${ALKIS_PG_TAG}
    container_name: ${ALKIS_PG_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - alkis_data:/var/lib/postgresql/data

volumes:
  alkis_data:
