networks:
  alkis_pg_net:
    driver: bridge

services:
  alkis_pg:
    image: ${ALKIS_PG_IMAGE:-alkis_pg}:${ALKIS_PG_TAG:-latest}
    container_name: ${ALKIS_PG_IMAGE:-alkis_pg}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-alkis_db}
      DEFAULT_CRS: ${DEFAULT_CRS:-25832}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - alkis_data:/var/lib/postgresql/data
    networks:
      - alkis_pg_net
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-alkis_db}",
        ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 5s

volumes:
  alkis_data:
